[package]
name = "clientrust"
version = "0.1.0"
edition = "2018"

[dependencies]
k256 = "0.9.4"
zeroize = "1.3.0"
rand = "0.8.4"
sha2 = "0.9.5"
hex-literal = "0.3.1"
crypto-bigint = "0.2.2"
arithmetic = "2.1.2"